server:
  port: 0
spring:
  application:
    name: api-serie
  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 5672
  zipkin:
    baseUrl: http://localhost:9411/
  data:
    mongodb:
      username: usr-catalog-mongo
      password: pwd-catalog-mongo
      database: catalog
      port: 27018
      host: localhost
info:
  application:
    name: api-serie
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
