server:
  port: 0
spring:
  application:
    name: api-catalog
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/movie-dev
    username: usr-movie
    password: pwd-movie
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
info:
  application:
    name: api-catalog
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

resilience4j:
  retry:
    configs:
      default:
        max-retry-attempts: 3
        wait-duration: 1s
        retry-exceptions:
          - java.io.IOException
          - java.net.SocketTimeoutException
      instances:
        retryCatalog:
          base-config: default
          max-retry-attempts: 1
          wait-duration: 2s
          retry-exceptions:
            - java.net.ConnectException
  circuitbreaker:
    configs:
      default:
        register-health-indicator: true
        sliding-window-size: 10
        minimum-number-of-calls: 5
        permitted-number-of-calls-in-half-open-state: 3
        wait-duration-in-open-state: 30s
        automatic-transition-from-open-to-half-open-enabled: true
        failure-rate-threshold: 50
    instances:
      clientCatalog:
        base-config: default
        sliding-window-type: COUNT_BASED
        sliding-window-size: 5
        wait-duration-in-open-state: 1m
        failure-rate-threshold: 20

